# Generated by Django 4.2.30 on 2026-06-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='shopping-bag', max_length=50)),
                ('icon_color', models.CharField(default='#2874f0', max_length=20)),
                ('bg_color', models.CharField(default='#f0f0f0', max_length=20)),
                ('image_base64', models.TextField(blank=True, null=True)),
                ('image_format', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='SliderImage',
        ),
    ]
