# Generated by Django 4.2.30 on 2026-06-18 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_category_name'),
        ('products', '0002_remove_brand_logo_remove_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
