# Generated by Django 4.2.30 on 2026-06-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_brand_category_brand_is_active_brand_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='logo',
        ),
    ]
